project: 
  type: website
  resources: 
    - "SDM-team.mp3"
  output-dir: docs
  render:
    - "*.*"
    - "!individual-folders/ben/*"
    - "!individual-folders/Catherine/*"
    - "!individual-folders/COB/*"
    - "!individual-folders/Eli/*"
    - "!individual-folders/Jade1/*"
    - "!individual-folders/Laura/*"
    - "!individual-folders/Mackenzie/*"
    - "!individual-folders/Mary/*"
    - "!individual-folders/Paulo/*"
    - "!tutorial/Subset*"
    - "maxnet/*"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2023 Ocean Hackweek"
  site-url: https://oceanhackweek.org/
  
  repo-url: https://github.com/oceanhackweek/ohw23_proj_marinesdms
  repo-actions: [edit, issue]
  
  page-footer: "2023 OceanHackWeek" 
 
  sidebar:
    logo: https://oceanhackweek.org/_static/logo.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://oceanhackweek.org/
        text: "OceanHackWeek"
      - icon: github
        href: https://github.com/oceanhackweek
        text: "GitHub"
    
    style: "docked"
    search: true
    collapse-level: 1
    toc-depth: 2
    contents:
      - text: "Welcome"
        href: index.md
      - section: Background
        contents:
          - text: "Roadmap"
            href: tutorial/Roadmap.Rmd
          - text: "Region"
            href: tutorial/00_Region.Rmd
          - text: "Marine Presence Data"
            href: tutorial/01_Presence_Data.Rmd
          - text: "Absence Data"
            href: tutorial/02_Background_Data.Rmd
          - text: "Environmental Variables"
            href: tutorial/03_sdmpredictors-variables.Rmd
          - text: "Models"
            href: tutorial/04_models.md
      - section: Our workflow
        contents:
          - text: "Presence Data"
            href: tutorial/seaturtle_robis.Rmd
          - text: "Absence Data"
            href: tutorial/background.Rmd
          - text: "Environmental Data"
            href: tutorial/occ_env.Rmd
      - section: Turtle SDMs!!
        contents:
          - text: "SDM"
            href: tutorial/Mackenzie_SDM_with_maxent.Rmd

format:
  html:
    theme:
      light: [cosmo] 
      dark: [cosmo]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto
