project: 
  type: website
  resources: 
    - "SDM-team.mp3"
  output-dir: docs
  render:
    - "*.*"
    - "!individual-folders/ben/*"
    - "!individual-folders/Catherine/*"
    - "!individual-folders/COB/*"
    - "!individual-folders/Eli/*"
    - "!individual-folders/Jade1/*"
    - "!individual-folders/Laura/*"
    - "!individual-folders/Mackenzie/*"
    - "!individual-folders/Mary/*"
    - "!individual-folders/Paulo/*"
    - "!tutorial/Subset*"
    - "!tutorial/Mackenzie_SDM_with_maxent_oops.Rmd"
    - "maxnet/*"
    - "!tutorial/Steps_Env.Rmd"
    - "!SDM/Turtle_GAM.Rmd"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "Marine SDMs"
  site-url: https://oceanhackweek.org/ohw23_proj_marinesdms
  favicon: "images/turtle.png"
  
  repo-url: https://github.com/oceanhackweek/ohw23_proj_marinesdms
  repo-actions: [edit, issue, source]
  
  page-footer: "OceanHackWeek Tutorial" 
 
  sidebar:
    logo: https://oceanhackweek.org/_static/logo.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://oceanhackweek.org/
        text: "OceanHackWeek"
      - icon: github
        href: https://github.com/oceanhackweek
        text: "GitHub"
    
    style: "docked"
    search: true
    collapse-level: 1
    toc-depth: 2
    contents:
      - text: "Welcome"
        href: index.md
      - section: Background
        href: tutorial/00_Roadmap.Rmd
        contents:
          - text: "Region"
            href: tutorial/00_Region.Rmd
          - text: "Presence data"
            href: tutorial/01_Presence_Data.Rmd
          - text: "Absence data"
            href: tutorial/02_Background_Data.Rmd
          - text: "Environmental data"
            href: tutorial/03_sdmpredictors-variables.Rmd
          - text: "Link envionment"
            href: tutorial/05_Link_env_to_pts.Rmd
          - text: "Types of models"
            href: tutorial/05_models.md
          - text: "Fitting models"
            href: tutorial/05_fitting.Rmd
      - section: SDM Steps
        contents:
          - text: "Save region objects"
            href: tutorial/Steps_Region.Rmd
          - text: "Save presence data"
            href: tutorial/Steps_occurences.Rmd
          - text: "Save absence aata"
            href: tutorial/Steps_background.Rmd
          - text: "Environmental Data"
            href: tutorial/Steps_occ_env.Rmd
          - text: "Fit with Maxnet"
            href: tutorial/Steps_sdm_maxnet.Rmd
          - text: "Visualization"
            href: tutorial/Steps_visualization.Rmd
      - section: Full SDM
        contents:
          - text: "Maxnet"
            href: SDM/Turtle_maxnet.Rmd
#          - text: "GAM"
#            href: SDM/Turtle_GAM.Rmd
        

format:
  html:
    theme:
      light: [cosmo] 
      dark: [cosmo]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto
